# Generated by Django 4.1 on 2022-12-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreResponsable', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('fechaReserva', models.DateField()),
                ('horaReserva', models.DateTimeField()),
                ('cantidadPersonas', models.IntegerField()),
                ('estado', models.CharField(max_length=90)),
                ('observacion', models.CharField(max_length=1000)),
            ],
        ),
    ]
